<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE trabajo [
<!ELEMENT trabajo (datos_principales, descripción, conocimientos_requeridos)>
<!ATTLIST trabajo CVs_inscritos CDATA #REQUIRED>
<!ATTLIST trabajo cantidad_puestos CDATA #FIXED "3">
<!ATTLIST trabajo fecha_publicación CDATA #FIXED "27/09/2024">
<!ELEMENT datos_principales (nombre_trabajo, empresa, ubicación, funcion, nivel_profesional, experiencia, formación_mínima, contrato)>
<!ELEMENT nombre_trabajo (#PCDATA)>
<!ELEMENT empresa (#PCDATA)>
<!ELEMENT ubicación (#PCDATA)>
<!ATTLIST ubicación residencia CDATA #REQUIRED>
<!ELEMENT funcion (#PCDATA)>
<!ELEMENT nivel_profesional (#PCDATA)>
<!ELEMENT experiencia (#PCDATA)>
<!ELEMENT formación_mínima (#PCDATA)>
<!ELEMENT contrato (tipo, salario)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT salario (#PCDATA)>
<!ATTLIST salario tipo CDATA #REQUIRED>
<!ELEMENT descripción (#PCDATA)>
<!ELEMENT conocimientos_requeridos (conocimiento+)>
<!ELEMENT conocimiento (#PCDATA)>
<!ATTLIST conocimiento años CDATA #IMPLIED>
]>
<trabajo CVs_inscritos="17" cantidad_puestos="3" fecha_publicación="27/09/2024">
    <datos_principales>
        <nombre_trabajo>Programador fullstack .NET y VUE</nombre_trabajo>
        <empresa>Arelance</empresa>
        <ubicación residencia="España">Teletrabajo</ubicación>
        <funcion>Programador</funcion>
        <nivel_profesional>Empleado</nivel_profesional>
        <experiencia>3 años</experiencia>
        <formación_mínima >FP2/Grado Superior</formación_mínima>
        <contrato>
            <tipo>Indefinido</tipo>
            <salario tipo="bruto">30.000 a 36.000€</salario>
        </contrato>
    </datos_principales>
    <descripción>En Arelance sabemos que las personas...</descripción>
    <conocimientos_requeridos>
        <conocimiento años="3">Desarrollo Front end con Vue 3 y Type script</conocimiento>
        <conocimiento años="3">Desarrollo backend con .NET (v. 5+)</conocimiento>
        <conocimiento años="1">Diseño APIs REST</conocimiento>
        <conocimiento>Git</conocimiento>
        <conocimiento>Docker y AzureSQL</conocimiento>
        <conocimiento>Azure DevOps Services y OAuth2</conocimiento>
    </conocimientos_requeridos>
</trabajo>