<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE matricula [
<!ELEMENT matricula (ciclo,alumnos)>
<!ELEMENT ciclo (#PCDATA)>
<!ELEMENT alumnos (alumno)+>
<!ELEMENT alumno (nombre,year,asignaturas)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT asignaturas (asignatura)+>
<!ELEMENT asignatura (#PCDATA)>

]>
<matricula>
    <ciclo>DAM</ciclo>
    <alumnos>
        <alumno>
            <nombre>Juan</nombre>
            <year>2025</year>
            <asignaturas>
                <asignatura>base de datos</asignatura>
                <asignatura>programación</asignatura>
            </asignaturas>
        </alumno>
        <alumno>
            <nombre>Marcos</nombre>
            <year>2025</year>
            <asignaturas>
                <asignatura>base de datos</asignatura>
                <asignatura>programación</asignatura>
            </asignaturas>
        </alumno>
    </alumnos>
</matricula>